---
abstract: 'Access Perl module, functions, variables through Riap'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Perinci::Examples: 0.08
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Access-Perl
requires:
  Class::Inspector: 0
  Log::Any: 0
  Module::List: 0
  Perinci::Access::Base: 0.30
  Perinci::Object: 0.11
  Perinci::Sub::Util: 0
  Perinci::Sub::Wrapper: 0.46
  Progress::Any: 0
  Riap: v1.1.19
  Rinci: v1.1.36
  SHARYANTO::ModuleOrPrefix::Path: 0
  SHARYANTO::Package::Util: 0
  Tie::Cache: 0
  URI::Split: 0
  UUID::Random: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci-Access-Perl
  repository: http://github.com/sharyanto/perl-Perinci-Access-Perl
version: 0.51
